server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false

---

spring:
  main:
    allow-bean-definition-overriding: true
    banner-mode: off
  config:
    activate:
      on-profile: integration-test

smallbank:
  ethereum:
    account: '0xfe3b557e8fb62b89f4916b721be55ceb828dbd73'
    private-key: '0x0083e05a7dac6a077adc1d7d1045b822b2d1d47b0e57c486b2eb17827a4a1eb56f'

logging:
  level:
    org.web3j.protocol: DEBUG
    org.springframework.web: DEBUG

---

# Görli Testnet

spring:
  main:
    banner-mode: off
  config:
    activate:
      on-profile: testnet

smallbank:
  ethereum:
    url: 'https://eth-goerli.alchemyapi.io/v2/blswUFyXkYK9XVYqgzGXtWa7N4Z8ZmWW'
    account: '0xf0e100995acbcc121305b9beba216cb7660f9c34'
    private-key: '0x0083e05a7dac6a077adc1d7d1045b822b2d1d47b0e57c486b2eb17827a4a1eb56f'
    chain-id: 5

logging:
  level:
    org.web3j.protocol: DEBUG
    org.springframework.web: WARN
