spring:
  main:
    allow-bean-definition-overriding: true
    banner-mode: off
  config:
    activate:
      on-profile: integration-test

smallbank:
  ethereum:
    account: '0xfe3b557e8fb62b89f4916b721be55ceb828dbd73'

logging:
  level:
    org.web3j.protocol: DEBUG
    org.springframework.web: DEBUG

---

# Görli Testnet

spring:
  config:
    activate:
      on-profile: testnet

smallbank:
  ethereum:
    url: 'https://eth-goerli.alchemyapi.io/v2/blswUFyXkYK9XVYqgzGXtWa7N4Z8ZmWW'
    account: '0xfe3b557e8fb62b89f4916b721be55ceb828dbd73'
    chain-id: 5

logging:
  level:
    org.web3j.protocol: DEBUG
    org.springframework.web: WARN
